name = "ReactantServerNode"
uuid = "49f09047-4fb9-4260-828b-8494ed8e9881"
version = "0.1.0"
authors = ["Carroll Vance <cvance@medicalmetrics.com>"]

[deps]
ReactantServerCore = "387a5f05-f7b4-4d57-bca9-cd3358e52bdc"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ReactantServerCore = "0.1"
YAML = "0.4.16"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[sources]
ReactantServerCore = {path = "../ReactantServerCore"}
