# Autogenerated using ProtoBuf.jl v1.3.0
# original file: reactant_control_v1.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export SetModelPolicyResponse, ModelControlStatusRequest, SetModelPolicyRequest, Residency
export SetModelResidencyRequest, ModelStatus, SetModelResidencyResponse
export ModelControlStatusResponse


struct SetModelPolicyResponse end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SetModelPolicyResponse}, _endpos::Int=0, _group::Bool=false)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return SetModelPolicyResponse()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SetModelPolicyResponse)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SetModelPolicyResponse)
    encoded_size = 0
    return encoded_size
end

struct ModelControlStatusRequest end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ModelControlStatusRequest}, _endpos::Int=0, _group::Bool=false)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return ModelControlStatusRequest()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ModelControlStatusRequest)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ModelControlStatusRequest)
    encoded_size = 0
    return encoded_size
end

struct SetModelPolicyRequest
    name::String
    has_weight::Bool
    weight::Float64
end
SetModelPolicyRequest(;name = "", has_weight = false, weight = zero(Float64)) = SetModelPolicyRequest(name, has_weight, weight)
PB.default_values(::Type{SetModelPolicyRequest}) = (;name = "", has_weight = false, weight = zero(Float64))
PB.field_numbers(::Type{SetModelPolicyRequest}) = (;name = 1, has_weight = 2, weight = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SetModelPolicyRequest}, _endpos::Int=0, _group::Bool=false)
    name = ""
    has_weight = false
    weight = zero(Float64)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            has_weight = PB.decode(d, Bool)
        elseif field_number == 3
            weight = PB.decode(d, Float64)
        else
            Base.skip(d, wire_type)
        end
    end
    return SetModelPolicyRequest(name, has_weight, weight)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SetModelPolicyRequest)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    x.has_weight != false && PB.encode(e, 2, x.has_weight)
    x.weight !== zero(Float64) && PB.encode(e, 3, x.weight)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SetModelPolicyRequest)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    x.has_weight != false && (encoded_size += PB._encoded_size(x.has_weight, 2))
    x.weight !== zero(Float64) && (encoded_size += PB._encoded_size(x.weight, 3))
    return encoded_size
end

@enumx Residency RESIDENCY_UNSPECIFIED=0 UNPINNED=1 PINNED_SYSTEM=2 PINNED_DEVICE=3

struct SetModelResidencyRequest
    name::String
    target::Residency.T
end
SetModelResidencyRequest(;name = "", target = Residency.RESIDENCY_UNSPECIFIED) = SetModelResidencyRequest(name, target)
PB.default_values(::Type{SetModelResidencyRequest}) = (;name = "", target = Residency.RESIDENCY_UNSPECIFIED)
PB.field_numbers(::Type{SetModelResidencyRequest}) = (;name = 1, target = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SetModelResidencyRequest}, _endpos::Int=0, _group::Bool=false)
    name = ""
    target = Residency.RESIDENCY_UNSPECIFIED
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            target = PB.decode(d, Residency.T)
        else
            Base.skip(d, wire_type)
        end
    end
    return SetModelResidencyRequest(name, target)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SetModelResidencyRequest)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    x.target != Residency.RESIDENCY_UNSPECIFIED && PB.encode(e, 2, x.target)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SetModelResidencyRequest)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    x.target != Residency.RESIDENCY_UNSPECIFIED && (encoded_size += PB._encoded_size(x.target, 2))
    return encoded_size
end

struct ModelStatus
    name::String
    residency::Residency.T
    device_resident::Bool
    host_resident::Bool
    weight_nbytes::Int64
    weight::Float64
    queue_depth::Int64
    total_compute_seconds::Float64
    requests_served::UInt64
    dispatch_count::UInt64
    max_batch_size::Int64
end
ModelStatus(;name = "", residency = Residency.RESIDENCY_UNSPECIFIED, device_resident = false, host_resident = false, weight_nbytes = zero(Int64), weight = zero(Float64), queue_depth = zero(Int64), total_compute_seconds = zero(Float64), requests_served = zero(UInt64), dispatch_count = zero(UInt64), max_batch_size = zero(Int64)) = ModelStatus(name, residency, device_resident, host_resident, weight_nbytes, weight, queue_depth, total_compute_seconds, requests_served, dispatch_count, max_batch_size)
PB.default_values(::Type{ModelStatus}) = (;name = "", residency = Residency.RESIDENCY_UNSPECIFIED, device_resident = false, host_resident = false, weight_nbytes = zero(Int64), weight = zero(Float64), queue_depth = zero(Int64), total_compute_seconds = zero(Float64), requests_served = zero(UInt64), dispatch_count = zero(UInt64), max_batch_size = zero(Int64))
PB.field_numbers(::Type{ModelStatus}) = (;name = 1, residency = 2, device_resident = 3, host_resident = 4, weight_nbytes = 5, weight = 6, queue_depth = 7, total_compute_seconds = 8, requests_served = 9, dispatch_count = 10, max_batch_size = 11)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ModelStatus}, _endpos::Int=0, _group::Bool=false)
    name = ""
    residency = Residency.RESIDENCY_UNSPECIFIED
    device_resident = false
    host_resident = false
    weight_nbytes = zero(Int64)
    weight = zero(Float64)
    queue_depth = zero(Int64)
    total_compute_seconds = zero(Float64)
    requests_served = zero(UInt64)
    dispatch_count = zero(UInt64)
    max_batch_size = zero(Int64)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            residency = PB.decode(d, Residency.T)
        elseif field_number == 3
            device_resident = PB.decode(d, Bool)
        elseif field_number == 4
            host_resident = PB.decode(d, Bool)
        elseif field_number == 5
            weight_nbytes = PB.decode(d, Int64)
        elseif field_number == 6
            weight = PB.decode(d, Float64)
        elseif field_number == 7
            queue_depth = PB.decode(d, Int64)
        elseif field_number == 8
            total_compute_seconds = PB.decode(d, Float64)
        elseif field_number == 9
            requests_served = PB.decode(d, UInt64)
        elseif field_number == 10
            dispatch_count = PB.decode(d, UInt64)
        elseif field_number == 11
            max_batch_size = PB.decode(d, Int64)
        else
            Base.skip(d, wire_type)
        end
    end
    return ModelStatus(name, residency, device_resident, host_resident, weight_nbytes, weight, queue_depth, total_compute_seconds, requests_served, dispatch_count, max_batch_size)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ModelStatus)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    x.residency != Residency.RESIDENCY_UNSPECIFIED && PB.encode(e, 2, x.residency)
    x.device_resident != false && PB.encode(e, 3, x.device_resident)
    x.host_resident != false && PB.encode(e, 4, x.host_resident)
    x.weight_nbytes != zero(Int64) && PB.encode(e, 5, x.weight_nbytes)
    x.weight !== zero(Float64) && PB.encode(e, 6, x.weight)
    x.queue_depth != zero(Int64) && PB.encode(e, 7, x.queue_depth)
    x.total_compute_seconds !== zero(Float64) && PB.encode(e, 8, x.total_compute_seconds)
    x.requests_served != zero(UInt64) && PB.encode(e, 9, x.requests_served)
    x.dispatch_count != zero(UInt64) && PB.encode(e, 10, x.dispatch_count)
    x.max_batch_size != zero(Int64) && PB.encode(e, 11, x.max_batch_size)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ModelStatus)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    x.residency != Residency.RESIDENCY_UNSPECIFIED && (encoded_size += PB._encoded_size(x.residency, 2))
    x.device_resident != false && (encoded_size += PB._encoded_size(x.device_resident, 3))
    x.host_resident != false && (encoded_size += PB._encoded_size(x.host_resident, 4))
    x.weight_nbytes != zero(Int64) && (encoded_size += PB._encoded_size(x.weight_nbytes, 5))
    x.weight !== zero(Float64) && (encoded_size += PB._encoded_size(x.weight, 6))
    x.queue_depth != zero(Int64) && (encoded_size += PB._encoded_size(x.queue_depth, 7))
    x.total_compute_seconds !== zero(Float64) && (encoded_size += PB._encoded_size(x.total_compute_seconds, 8))
    x.requests_served != zero(UInt64) && (encoded_size += PB._encoded_size(x.requests_served, 9))
    x.dispatch_count != zero(UInt64) && (encoded_size += PB._encoded_size(x.dispatch_count, 10))
    x.max_batch_size != zero(Int64) && (encoded_size += PB._encoded_size(x.max_batch_size, 11))
    return encoded_size
end

struct SetModelResidencyResponse
    residency::Residency.T
end
SetModelResidencyResponse(;residency = Residency.RESIDENCY_UNSPECIFIED) = SetModelResidencyResponse(residency)
PB.default_values(::Type{SetModelResidencyResponse}) = (;residency = Residency.RESIDENCY_UNSPECIFIED)
PB.field_numbers(::Type{SetModelResidencyResponse}) = (;residency = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SetModelResidencyResponse}, _endpos::Int=0, _group::Bool=false)
    residency = Residency.RESIDENCY_UNSPECIFIED
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            residency = PB.decode(d, Residency.T)
        else
            Base.skip(d, wire_type)
        end
    end
    return SetModelResidencyResponse(residency)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SetModelResidencyResponse)
    initpos = position(e.io)
    x.residency != Residency.RESIDENCY_UNSPECIFIED && PB.encode(e, 1, x.residency)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SetModelResidencyResponse)
    encoded_size = 0
    x.residency != Residency.RESIDENCY_UNSPECIFIED && (encoded_size += PB._encoded_size(x.residency, 1))
    return encoded_size
end

struct ModelControlStatusResponse
    residency_mode::String
    discipline::String
    models::Vector{ModelStatus}
    weight_cache_max_bytes::UInt64
end
ModelControlStatusResponse(;residency_mode = "", discipline = "", models = Vector{ModelStatus}(), weight_cache_max_bytes = zero(UInt64)) = ModelControlStatusResponse(residency_mode, discipline, models, weight_cache_max_bytes)
PB.default_values(::Type{ModelControlStatusResponse}) = (;residency_mode = "", discipline = "", models = Vector{ModelStatus}(), weight_cache_max_bytes = zero(UInt64))
PB.field_numbers(::Type{ModelControlStatusResponse}) = (;residency_mode = 1, discipline = 2, models = 3, weight_cache_max_bytes = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ModelControlStatusResponse}, _endpos::Int=0, _group::Bool=false)
    residency_mode = ""
    discipline = ""
    models = PB.BufferedVector{ModelStatus}()
    weight_cache_max_bytes = zero(UInt64)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            residency_mode = PB.decode(d, String)
        elseif field_number == 2
            discipline = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, models)
        elseif field_number == 4
            weight_cache_max_bytes = PB.decode(d, UInt64)
        else
            Base.skip(d, wire_type)
        end
    end
    return ModelControlStatusResponse(residency_mode, discipline, models[], weight_cache_max_bytes)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ModelControlStatusResponse)
    initpos = position(e.io)
    !isempty(x.residency_mode) && PB.encode(e, 1, x.residency_mode)
    !isempty(x.discipline) && PB.encode(e, 2, x.discipline)
    !isempty(x.models) && PB.encode(e, 3, x.models)
    x.weight_cache_max_bytes != zero(UInt64) && PB.encode(e, 4, x.weight_cache_max_bytes)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ModelControlStatusResponse)
    encoded_size = 0
    !isempty(x.residency_mode) && (encoded_size += PB._encoded_size(x.residency_mode, 1))
    !isempty(x.discipline) && (encoded_size += PB._encoded_size(x.discipline, 2))
    !isempty(x.models) && (encoded_size += PB._encoded_size(x.models, 3))
    x.weight_cache_max_bytes != zero(UInt64) && (encoded_size += PB._encoded_size(x.weight_cache_max_bytes, 4))
    return encoded_size
end

# SERVICE: No codegen handlers registered
#    ControlService
