name = "ReactantServerGateway"
uuid = "b92f1031-7cb7-4fde-89de-b6dd50303018"
version = "0.1.0"
authors = ["Carroll Vance <cvance@medicalmetrics.com>"]

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Prometheus = "f25c1797-fe98-4e0c-b252-1b4fe3b6bde6"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
ReactantServerCore = "387a5f05-f7b4-4d57-bca9-cd3358e52bdc"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
gRPCClient = "aaca4a50-36af-4a1d-b878-4c443f2061ad"
gRPCServer = "b7f0dee4-5e6a-42e7-93b0-9c098bad2317"

[compat]
HTTP = "2"
Prometheus = "1.4"
ProtoBuf = "1.3.0"
ReactantServerCore = "0.1"
YAML = "0.4.16"
gRPCClient = "1.0.3"
gRPCServer = "0.1"
julia = "1.12"

[extras]
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Sockets"]

[sources]
ReactantServerCore = {path = "../ReactantServerCore"}
Prometheus = {path = "../../lib/Prometheus.jl"}
gRPCServer = {path = "../../lib/gRPCServer.jl"}
gRPCClient = {path = "../../lib/gRPCClient.jl"}
HTTP = {path = "../../lib/HTTP.jl"}
